### ISSUE TITLE
demo app not working on windows "Command Prompt"

### ISSUE THREAD

**Issue by itsmpk88** [facebookincubator/fbt#11]
Due to find the command. Find command won't work in windows.

**Windows Command screenshot:**

![image](https://user-images.githubusercontent.com/13304182/50659541-d8e56700-0f94-11e9-9c2e-1a0f8300b9bb.png)

**Unix Command Screenshot**

![image](https://user-images.githubusercontent.com/13304182/50659591-0205f780-0f95-11e9-9282-93263cadd8bc.png)

**Comment by jrwats** [comment]
Fixed in [this pull request](https://github.com/facebookincubator/fbt/pull/5)
I'd recommend pulling that change in while we're still waiting for that merge to come through.

**Comment by itsmpk88** [comment]
> Fixed in [this pull request](https://github.com/facebookincubator/fbt/pull/5)
> I'd recommend pulling that change in while we're still waiting for that merge to come through.

@jrwats  Now "yarn build" not working on Windows. 

![image](https://user-images.githubusercontent.com/13304182/50660324-45f9fc00-0f97-11e9-89e3-258fa0e3742f.png)

**Comment by jrwats** [comment]
Did you run `yarn install`, `yarn manifest` and `yarn translate-fbts` beforehand?

**Comment by itsmpk88** [comment]
@jrwats yes.

![image](https://user-images.githubusercontent.com/13304182/50661938-9de73180-0f9c-11e9-880d-e31c8df49b85.png)

**Comment by itsmpk88** [comment]
Actually I fixed those issues and make the demo-app working on windows. 

01. Run on the application only "Git Bash" for windows.
02. install the webpack plugin in base folder "fbt"

![image](https://user-images.githubusercontent.com/13304182/50662162-62993280-0f9d-11e9-9eb2-8223f03f3e1c.png)

**Comment by jrwats** [comment]
@itsmpk88, glad you got it working!  Can you paste the entire error you had when loading from `yarn build` though?

**Comment by itsmpk88** [comment]
@jrwats 

![image](https://user-images.githubusercontent.com/13304182/50664552-5f09a980-0fa5-11e9-8e99-00e5d1add7cc.png)

Fix is in package.json

just replace 

> ".. to ."

![image](https://user-images.githubusercontent.com/13304182/50664676-d0e1f300-0fa5-11e9-8da5-a1d5966be8ae.png)

**Comment by jrwats** [comment]
OK - this should be fixed with https://github.com/facebookincubator/fbt/pull/14
