### ISSUE TITLE
Remove FbtCommonConstants from babel-plugin-fbt

### ISSUE THREAD

**Issue by fruchtose** [facebookincubator/fbt#110]
## 🚀 Feature Proposal

`babel-plugin-fbt` currently contains the following dictionary of Facebook-specific strings in the library, used for the `common` API: https://github.com/facebookincubator/fbt/blob/cf5743af96e48ce49cda9f3258c5d1102684f1b7/packages/babel-plugin-fbt/FbtCommonConstants.js

Developers should be able to register their own set of common strings, instead.

## Motivation

This proposal relates to #108. For the common string API to be useful, developers need to be able to say which strings are constant.

## Example

A developer could provide a JSON file which contains a dictionary of common strings. For instance, this might be part of the `collectFBT` command:

```bash
node ./node_modules/babel-plugin-fbt/bin/collectFBT --commonSrc ./config/i18n/commonStrings.json --manifest < .fbt/src_manifest.json > .fbt/source_strings.json
```

## Pitch

This feature would be useful for the same reason #108 would be useful: it would empower teams to do more with FBT.

**Comment by jrwats** [comment]
https://github.com/facebookincubator/fbt/commit/26c5cd8b2019eeae21d1790fb46c9cc2edf2e89d

and published in: babel-plugin-fbt@0.12.0
