### ISSUE TITLE
Unable to import intlList

### ISSUE THREAD

**Issue by wmichelin** [facebookincubator/fbt#123]
## 🐛 Bug Report

Following code examples from https://facebookincubator.github.io/fbt/docs/utilities/, I am unable to use the `intlList` module.

## To Reproduce

- Clone clean fbt repo.
- Build fbt repo
- Follow instructions to build sample app https://github.com/facebookincubator/fbt/blob/master/demo-app/README.md
- Apply changes described by https://github.com/facebookincubator/fbt/compare/master...wmichelin:issue-example
- Attempt to build

## Expected behavior
The application would build, allowing me to use the `intlList` module.

## Link to repo (highly encouraged) or paste
https://github.com/facebookincubator/fbt/compare/master...wmichelin:issue-example

## envinfo

```bash
  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 55.59 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.12.0 - ~/.nvm/versions/node/v12.12.0/bin/node
    Yarn: 1.21.1 - ~/.nvm/versions/node/v12.12.0/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v12.12.0/bin/npm
```

**Comment by kayhadrin** [comment]
This is a documentation error.

`intlList` is meant to be imported from the `fbt` npm package.
Trying to import it like `require('intlList')` assumes that it was either an npm package itself, or pre-processed from some Babel transform (which isn't the case).

**Comment by jrwats** [comment]
> intlList is meant to be imported from the fbt 

And should probably be exposed... :P  Right now the only way to reference it is via its path (a general no-no).
