### ISSUE TITLE
Cannot run demo app

### ISSUE THREAD

**Issue by saranshkataria** [facebookincubator/fbt#15]
When I run yarn install on windows, I get:

error An unexpected error occurred: "ENOTDIR: not a directory, scandir 'D:\\fbt\\demo-app\\node_modules'".

I think it has to do with there being an existing file/link (not sure what that is) in the directory. If anyone can guide me to it's purpose, would be happy to send in a PR that resolves this

**Comment by jrwats** [comment]
@kayhadrin tells me it's due to the symlink.  While waiting for this to merge in, you can try this fix for yourself:
https://github.com/facebookincubator/fbt/pull/14

**Comment by saranshkataria** [comment]
That fixes it for me. Closing this issue out!
