### ISSUE TITLE
Does fbt support splitting translationGroups by locale into different files

### ISSUE THREAD

**Issue by YaoKaiLun** [facebookincubator/fbt#24]
I see the field translationGroups in translation_input.json includes many locales, but the file seems too large when you have a lot of translations. So, does fbt or babel-plugin-fbt support splitting translationGroups into different files?

**Comment by jrwats** [comment]
It *should*, but doesn't currently.  Let's get on top of that.

**Comment by jrwats** [comment]
See the following commits:
[Supporting multiple translation files](https://github.com/facebookincubator/fbt/commit/93efdec7a49382a3b7bac16281f6254224bb9005)
[Splitting demo translations into separate files](https://github.com/facebookincubator/fbt/commit/ea9e9fad31cf251f3e0e942930b5f9a82e10482f)
