### ISSUE TITLE
Does fbt support html strings?

### ISSUE THREAD

**Issue by m1m6** [facebookincubator/fbt#30]
Hey, thanks for the nice package,

I have a question, does fbt support html string string?
like in react-intl theres formatHTMLmessage method that accept html element like:
`formatHTMLmessage ('id','<span>test html string</span>')`

does fbt support this?

**Comment by jrwats** [comment]
FBT supports this inherently by way of the Babel JSX-transform upon which it relies.  You can effectively write the above example in fbt as:
```
<span>
  <fbt desc="example">
    test html string
  </fbt>
</span>
```
