### ISSUE TITLE
[docs] add docs of how to integrate with an existing react app

### ISSUE THREAD

**Issue by sibelius** [facebookincubator/fbt#48]
it would be great to have a step by step tutorial on docs of how to setup fbt in an existing React app project

which packages should we install?
how should we modify our babel config?
should we modify our webpack config?
how to translate new generated hash keys?

**Comment by ahmadalfy** [comment]
I am kind of confused how can I use it, I checked the example app and didn't find any packages called `fbt` in `package.json`. Also all the references I can find on npm is [this](https://www.npmjs.com/package/fbt-cli) and it doesn't say anything

**Comment by jrwats** [comment]
> I am kind of confused how can I use it, I checked the example app and didn't find any packages called `fbt` in `package.json`. Also all the references I can find on npm is [this](https://www.npmjs.com/package/fbt-cli) and it doesn't say anything

I have no idea what fbt-cli is, but the packages used in the demo-app are actually using the yarn workspaces.  You can look at my example npm-only app for the relevant npm modules:
https://github.com/jrwats/fbt-npm-app

We should be landing and finalizing version 1.0.0 for all of these modules this week.

**Comment by ahmadalfy** [comment]
@jrwats thank you so much for your effort, I checked the new version again. It's still not user friendly I have been trying to get it to work in my existing project without any success. I will continue to tinker and document the steps in a format an average developer can understand.

**Comment by aldeka** [comment]
A +1 on this issue -- even after guessing at a bunch of steps (e.g. manually installing babel-node and related dependencies globally) by reading the sample app's package.json, we were unable to get fbt working in our existing application. fbt's promised feature set is super great, but right now there is zero documentation for consumers of the library to get started (versus developers building the library from source). :(

**Comment by retyui** [comment]
It took me an hour to add **fbt** to my react-native project.

@aldeka You don't need `babel-node` to run scripts from an npm package!

**Comment by retyui** [comment]
You can find diff for `create-react-app` project [here...](https://github.com/retyui/fbt-getting-started/commit/969e17ab7991942217691cf3ad7fb7c76ea92b31)

**Comment by Zbish** [comment]
> It took me an hour to add **fbt** to my react-native project.
> 
> @aldeka You don't need `babel-node` to run scripts from an npm package!

can u upload a diff or sample  for
 react-native app works with fbt ???

**Comment by retyui** [comment]
@Zbish  there is no big difference, you can use [this diff](https://github.com/retyui/fbt-getting-started/commit/969e17ab7991942217691cf3ad7fb7c76ea92b31)

**Comment by Zbish** [comment]
thanks,  will try
and it will work on react-native init app ??

**Comment by retyui** [comment]
Migrate to the latest version https://github.com/retyui/fbt-getting-started/commit/6d55f47a57f34e93edc53b410ec64f97916e30f1

**Comment by vhesener** [comment]
> thanks, will try
> and it will work on react-native init app ??

@Zbish Did you ever get this working? Wondering if I should attempt to integrate into a React Native app or not. I can't seem to find anyone using it successfully

**Comment by jrwats** [comment]
@vhesener, @Zbish, @retyui: here's some breaking news we haven't announced yet... 

We released the **Android**  [NPM package](https://github.com/facebookincubator/fbt/tree/rn-demo-app) and [demo-app](https://github.com/facebookincubator/fbt/tree/rn-demo-app).  Take a look and let @dalmendray know if you hit any issues :)

**Comment by vhesener** [comment]
I understand there's a demo app that proves this can work, but I think there's a slight disconnect in what we were expecting. I'm willing to help you get there, but I just need to know what steps need to be taken to bring this functionality into an existing React (Native) app.

There seems to be some missing magic to get from [here](https://facebookincubator.github.io/fbt/docs/getting_started) to [here](https://facebookincubator.github.io/fbt/docs/api_intro). For example, where are the install steps and where are the `import` statements? Package documentation usually includes a typical cadence in the beginning pages in the docs. Here's a pseudo outline of what I would like to see before I know if I can use a any given package: 

---

#### Installation

1. Add dependencies: `yarn add fbt` or maybe even `yarn add https://github.com/facebookincubator/fbt`.
1. add plugin to babel
1. if using RN version < 0.60, do some manual linking stuff

#### Getting Started
1. `import { fbt } from  'fbt';`
1. Add some Provider to the app
1. Use the `<fbt />` component

---

I understand it's probably not too much effort to clone the demo app and figure out how to massage this to a working state. I'm not being lazy here, but I just want to know this use case is even supported and if you intend to add this type of documentation for future tinkerers. Candidly, if no one is using this package in a traditional way, I am reluctant to be on the fringe. There's strength in numbers with a larger community sharing the same problem sets. 

Let me know your thoughts and if we can help. I think many of us would be willing to help you polish the usability if you were to share your vision regarding app integrations.

**Comment by jrwats** [comment]
@vhesener, @sibelius  feel free to comment on this
https://github.com/facebookincubator/fbt/pull/126

**Comment by Zbish** [comment]
> > thanks, will try
> > and it will work on react-native init app ??
> 
> @Zbish Did you ever get this working? Wondering if I should attempt to integrate into a React Native app or not. I can't seem to find anyone using it successfully

yes working great in react-native app
but it was not easy to set all to work fine

**Comment by jrwats** [comment]
## Documentation
@sibelius 
> how to translate new generated hash keys?

We should probably add a section giving a bit more detail under the "Translations".  I don't think it necessarily belongs in "Getting Started".

### React Native
@Zbish  @vhesener
Regarding React Native, We should have some docs getting published this week for using the [recently released NPM Android package](https://www.npmjs.com/package/fbt-rn-android-native).

**Comment by jrwats** [comment]
Closing this out for now with 
https://github.com/facebookincubator/fbt/commit/7cfe6659e17a75b80494e2fc219cd309a89174ae and https://github.com/facebookincubator/fbt/commit/12558f6e40cec723aeb3294ae97ed1f2383ffd26 now live.

@sibelius, @vhesener, if you feel [the documentation](https://facebookincubator.github.io/fbt/docs/getting_started) is still lacking, feel free to re-open.

If you think it can be improved, we'll gladly look at any PRs you have!
