### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by sibelius** [facebookincubator/fbt#49]
Manifest and maybe other cli should support .ts and .tsx files

I think the transform will just work as babel 7 supports typescript

**Comment by sibelius** [comment]
collectFBT also throws when parsing typescript files with babel

```jsx
Error: [BABEL] unknown: Configuration contains string/RegExp pattern, but no filename was passed to Babel
/entria-fullstack/node_modules/babel-plugin-fbt/bin/collectFBT.js:131
    throw new Error(`Failed in ${errCount} files`);
    ^

Error: Failed in 1 files
    at writeOutput (/entria-fullstack/node_modules/babel-plugin-fbt/bin/collectFBT.js:131:11)
    at ReadStream.<anonymous> (/entria-fullstack/node_modules/babel-plugin-fbt/bin/collectFBT.js:169:5)
```

**Comment by sibelius** [comment]
after https://github.com/facebookincubator/fbt/pull/51

I've got this error:

```jsx
Error: Line 37 Column 11: `fbt` is not bound. Did you forget to require('fbt')?
/entria-fullstack/node_modules/babel-plugin-fbt/bin/collectFBT.js:131
    throw new Error(`Failed in ${errCount} files`);
    ^

Error: Failed in 1 files
    at writeOutput (/entria-fullstack/node_modules/babel-plugin-fbt/bin/collectFBT.js:131:11)
    at ReadStream.<anonymous> (/entria-fullstack/node_modules/babel-plugin-fbt/bin/collectFBT.js:169:5)
    at ReadStream.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

it could be related to https://github.com/facebookincubator/fbt/issues/46

**Comment by sibelius** [comment]
this could help https://github.com/sibelius/codemod-RN24-to-RN25/blob/master/transform.js#L22

**Comment by kayhadrin** [comment]
1. Support for Typescript files is certainly on our radar but not scheduled yet.
2. Re: the error about the absence of `require('fbt')`. That check was useful before when we had no proper way to check that `fbt` was a defined variable in the JS module scope. Now that we've got better `Flow` support, we can remove this.

**Comment by baluubas** [comment]
@kayhadrin Do you have any pointers where that check is made? I wouldn't mind keeping a fork going until things are ready for typescript support.

**Comment by sibelius** [comment]
@baluubas you can use my 2 pull requests 

https://github.com/facebookincubator/fbt/pull/50
https://github.com/facebookincubator/fbt/pull/51

**Comment by kayhadrin** [comment]
@baluubas I believe @sibelius answered your question.

**Comment by kayhadrin** [comment]
@sibelius Re: https://github.com/facebookincubator/fbt/issues/49#issuecomment-462069077

Could you provide an example of how you're importing `fbt` in your JS module?

I assume it's something like this:

```
import fbt from 'fbt';
// or
import {fbt} from 'fbt';
```

**Comment by sibelius** [comment]
I’m using export default

Checking the code, I could use named or export default

For me, anyone of them could work

**Comment by kayhadrin** [comment]
I've applied the your two PRs locally (#50 and #51), 
converted the `demo-app/src/example/Example.react.js` file to `tsx`,
ran `yarn manifest` and `yarn collect-fbts` and it worked successfully.

If that's still an issue on your side, you may want to submit the minimum repro code in a Codepen.

**Comment by AndrewCraswell** [comment]
It seems the pull requests were merged, can this issue be closed or is Typescript still not fully supported?

**Comment by jrwats** [comment]
I'll close for now, and if any further issues arise, we can investigate.

**Comment by retyui** [comment]
Here is an article about  [Typescript + fbt](https://bit.ly/3bUrxM7) where I describe problems that i faced and how to fix them
