### ISSUE TITLE
Allow additional babel plugins in FbtCollector

### ISSUE THREAD

**Issue by pwalczyszyn** [facebookincubator/fbt#53]
I have a project where I use decorators, when I run collect operation it fails as it doesn't have proper babel plugins configured for my source code.

**Comment by jrwats** [comment]
Yup.  I actually intend to tackle this.  It bit us in our split codebases recently.

**Comment by jrwats** [comment]
As of [5bb45673677e5b0a104d5d99550eeb87f5f905f7](https://github.com/facebookincubator/fbt/commit/5bb45673677e5b0a104d5d99550eeb87f5f905f7), this is fixed with an additional `--plugins` arg to the `collect-fbts` script.
