### ISSUE TITLE
yarn manifest出现错误?

### ISSUE THREAD

**Issue by 1655119603** [facebookincubator/fbt#58]
你好,我按照这边提供的命令初始化该项目,但是yarn install之后到了yarn manifest生成文件时出现问题,请问能帮我看一下这是有什么问题导致的吗?
![QQ截图20190403111654](https://user-images.githubusercontent.com/41121802/55450540-142e1b00-5602-11e9-9eff-40f044b260ec.png)

**Comment by 1655119603** [comment]
user [yarn manifest] this commed does face the same wrong as usual

**Comment by kayhadrin** [comment]
I presume you're saying that the `yarn manifest` command does not work on Windows?
It'd be great if you could translate your bug summary to English ^^..

**Comment by kayhadrin** [comment]
From your screenshot, I think you ran the `yarn manifest` command from the incorrect folder.
Could you try the commands as per our [README: Installing fbt](https://github.com/facebookincubator/fbt#installing-fbt)?

![image](https://user-images.githubusercontent.com/182644/55459491-8ff97a80-55a4-11e9-91a9-f487fe1e0e5d.png)
(attached screenshot for posterity)

**Comment by w1106c** [comment]
从你的截图来看，你好像跑的命令是yarn manifest**s**, 后边多了一个s。
