### ISSUE TITLE
Remove Banzai?

### ISSUE THREAD

**Issue by Daniel15** [facebookincubator/fbt#59]
https://github.com/facebookincubator/fbt/blob/7f90309e56b6ba2126ca6b097756c5fbd8d4666e/runtime/shared/fbt.js#L455

This is a Facebook-ism that we probably don't want to keep in the open source release. Perhaps it should have a hook to set a logger (eg. `fbt.setLogger(....)`) rather than having a hard dependency on Banzai (which is mocked out in this open source release).

**Comment by jrwats** [comment]
We have a TON of (production) mocks right now that could probably be dealt with a bit better.  So yeah - in the very least we can tackle this.

**Comment by jrwats** [comment]
Fixed in GitHub with https://github.com/jrwats/fbt/commit/630dea5b803b369d9cfcd6fa32c48cc0b06cd674 and is published to [fbt 0.11.0](https://www.npmjs.com/package/fbt/v/0.11.0)
