### ISSUE TITLE
Question on plurals

### ISSUE THREAD

**Issue by jleclanche** [facebookincubator/fbt#6]
Hi! Thanks for open sourcing this. Looks exciting!

Plural handling jumped out at me as very basic:
https://facebookincubator.github.io/fbt/docs/plurals

As is, it looks like a simplistic-yet-very-specific one/many handling with support for showing a counter.
Since fbt is used at Facebook (a product with a pretty involved translation) I'm curious if that is actually enough for Facebook itself?

For context, several languages (Russian for example) have many types of plurals. The ICU message syntax is my go-to for supporting these cases:
http://userguide.icu-project.org/formatparse/messages (it is used by [FormatJS](https://formatjs.io/guides/message-syntax/#plural-format) so should be familiar to users of formatjs projects).

**Comment by jrwats** [comment]
The magic is tucked away in translations actually (we need to improve our documentation surrounding this).  The CLDR number type corresponding to "RU" is [IntlCLDRNumberType30](https://github.com/facebookincubator/fbt/blob/master/runtime/shared/FbtNumber/IntlCLDRNumberType30.js).  A translator can variate your individual source for a translation for any given token in the source.  In the example's case, this would be `{number of likes}` in `"You have {number of likes} likes on your photos"`.  So we could have variations for ONE, FEW, or MANY here.

You can see some examples of gender variations for the hidden token, `__viewer_gender__` [in our translation_input.json](
https://github.com/facebookincubator/fbt/blob/master/demo-app/translation_input.json#L443).

I also suspect we're missing number variations in our [Arabic translation for d47b9415c39a6e5e042244d77c23bb13](https://github.com/facebookincubator/fbt/blob/master/demo-app/translation_input.json#L1928), but I'm checking on that internally.

I'll work on making this clearer in documentation!

**Comment by jrwats** [comment]
You can see all the variation types available for any given translation leaf here:
https://facebookincubator.github.io/fbt/docs/translating#variation-types

**Comment by jrwats** [comment]
OK.  Pulled in more accurate AR translations for this. https://github.com/facebookincubator/fbt/blob/master/demo-app/translation_input.json#L1932-L1979
You can see how they are variated in the demo itself as well.

Let me know if you have any more questions around this!
