### ISSUE TITLE
Getting Started page doesn't work with latest yarn

### ISSUE THREAD

**Issue by maxsbelt** [facebookincubator/fbt#61]
I try to run getting started page instructions with latest version of `yarn` package (`1.15.2`) and getting error `babel-node: command not found`. Command works property with some previous versions of `yarn` (`1.10.0`). Also everything works property if I using `npm run` command. Maybe it's better to replace scripts commands with `npm run`?

<img width="899" alt="Screenshot 2019-05-04 at 12 20 35" src="https://user-images.githubusercontent.com/950216/57176933-22709080-6e67-11e9-9332-716a9f9fba8e.png">

Link to gettings started instructions:
https://facebookincubator.github.io/fbt/docs/getting_started

**Comment by jrwats** [comment]
Looks like a bug in yarn's `modules-folder`.
https://github.com/yarnpkg/yarn/pull/6850/files#diff-46e3111748d572a99398769469253279R100
Should have been `path.resolve`

cc. @rally25rs, @arcanis

**Comment by jrwats** [comment]
We don't need these `.yarnrc` files with yarn workspaces, so let's just remove them and avoid this `modules-folder` bug.

**Comment by jrwats** [comment]
Should be fixed with commit:
https://github.com/facebookincubator/fbt/commit/425cc53b6be249ccc3904d03ad77226c0f88eb4f
