### ISSUE TITLE
`intlList` has incorrect relative imports in npm package, can't require with webpack

### ISSUE THREAD

**Issue by jack-arms** [facebookincubator/fbt#62]
In the npm package for fbt, 0.9.5, in node_modules, `fbt/lib/intlList.js` has this for line 25:
```
var React = require("./React");
```
However, there's no React in the `lib` folder so with webpack it fails to resolve `require('fbt/lib/intlList')`. In the source file though, https://github.com/facebookincubator/fbt/blob/master/runtime/shared/intlList.js, there's an absolute import for React, `const React = require('React')`.

Is this an error? And if so can we update the version of the npm package?

**Comment by jrwats** [comment]
I suspect this is a bug in the [gulpfile](https://github.com/facebookincubator/fbt/blob/master/gulpfile.js) that produces these distributions

**Comment by jrwats** [comment]
To be specific, we need to blacklist React and other packages (not owned by FBT) when converting relative paths to absolute.
