### ISSUE TITLE
Running the live-demo-app is not in sync with its instruction

### ISSUE THREAD

**Issue by udielenberg** [facebookincubator/fbt#69]
Hey

I've  tried to run the live-demo-app together with (@jrwats  [youtube-instructions](https://www.youtube.com/watch?v=7XW3SkWsaKo)), and followed the instructions in the `README`.

```
yarn manifest
yarn collect-fbts
yarn translate-fbts
yarn build
yarn start
```

when I try to switch between langauges nothing changes (beside `align-right` of RTL languages)
![Screen Shot 2019-08-12 at 10 51 16](https://user-images.githubusercontent.com/39482108/62851564-3c83ff80-bcef-11e9-9f01-c4fc73c0f900.png)

How do I  _activate_ the translations ?

**Comment by udielenberg** [comment]
Kinda found the problem

The actual **demo app** is `demo-app` and not `demo-app-live`.

so all is good 👍

**Comment by jrwats** [comment]
Yeah... live-demo-app's intended use was for demo'ng live and uncommenting fbt instances to show how it worked. It's effectively demo-app with fbt instances individually commented out
