### ISSUE TITLE
Code splitting translation

### ISSUE THREAD

**Issue by AdamRamberg** [facebookincubator/fbt#71]
First of all, thanks for making fbt open source! 🙏 

Currently the [transform script](https://github.com/facebookincubator/fbt/blob/master/transform/babel-plugin-fbt/bin/translate.js) only outputs a single file, which in the application gets passed to the fbt's init function. This means that we need to load all translations at once! Are there any plans on supporting generating multiple translation files that could then be dynamically loaded by fbt when needed? For starters it would for example be nice to split translations on locale.

**Comment by jrwats** [comment]
> First of all, thanks for making fbt open source! 🙏

Much obliged :)

> in the application gets passed to the fbt's init function. This means that we need to load all translations at once!

Well that's what the demo currently *does*, but even with the way the the `transform` script is currently written, you could elect to create a separate dictionary for each language and `init` whenever you want to load a new one (or your async pull request comes back etc etc).  If it'd be helpful I can update https://github.com/jrwats/fbt-npm-app to do this.

But even better... I'll gladly review any pull request you'd like to make to ease the pain using the translation script.  It'd be nice, for instance, if you could run the script once instead of per locale.

**Comment by AdamRamberg** [comment]
Ah alright! Great to hear that `init` supports being called once per locale. 

I agree that it would be really nice if you only need to run the translation script once. I'm currently pretty swamped with work so I will not make any promises, but if I find the time I will for sure make a PR. 

Not closing the issue since it might be nice to keep it open until the translation script has been worked on.

**Comment by jrwats** [comment]
@AdamRamberg, check out [this commit here](https://github.com/jrwats/fbt-npm-app/commit/7b2d4b5449e52d41e0f503270248e58c3753dbb9) in the [fbt-npm-app](https://github.com/jrwats/fbt-npm-app) repo for an example on splitting dictionaries by locale.  I'm using [webpack's dynamic import](https://webpack.js.org/guides/code-splitting/) syntax [in the Example react app](https://github.com/jrwats/fbt-npm-app/blob/master/src/example/Example.react.js#L101) for this.

I'm just appending to the "translation dictionary" (which FBT's `init` is hanging onto) [as seen here](https://github.com/jrwats/fbt-npm-app/blob/master/src/example/Example.react.js#L103).

Incorporating [this logic](https://github.com/jrwats/fbt-npm-app/commit/7b2d4b5449e52d41e0f503270248e58c3753dbb9#diff-1a7b9a011efcf95ba8bfff783946acdd) into translate.js itself should be straightforward.

Note: You'll need the `babel-plugin-fbt` module version `0.9.13` for the `--plugins` CLI option if you intend to use the babel transform for dynamic import.

**Comment by AdamRamberg** [comment]
@jrwats Awesome! Thanks! 

Shouldn't be too hard to implement the splitting by locale in [translate.js](https://github.com/facebookincubator/fbt/blob/master/transform/babel-plugin-fbt/bin/translate.js). I will take a stab at it and make PR.
