### ISSUE TITLE
Remove test files from published npm package

### ISSUE THREAD

**Issue by retyui** [facebookincubator/fbt#80]
Can you remove tests\mock files?

- [babel-plugin-fbt@0.9.16](https://unpkg.com/browse/babel-plugin-fbt@0.9.16/)

```
/translate/__tests__
/bin/__tests__
/__mocks__
/__tests__
```

- [babel-plugin-fbt-runtime@0.9.4](https://unpkg.com/browse/babel-plugin-fbt-runtime@0.9.4/)

```
/__tests__
```

**Comment by jrwats** [comment]
@bmhaskar did this in https://github.com/facebookincubator/fbt/pull/81
