### ISSUE TITLE
Need to support unit tests for open-source

### ISSUE THREAD

**Issue by kayhadrin** [facebookincubator/fbt#84]
The unit tests we [have](https://github.com/facebookincubator/fbt/tree/master/runtime/shared/__tests__) can only be run in our internal test infra.

We need to create a new Jest config to make it testable in a stand-alone environment (outside FB infra).

Ideally, it could then be run on Travis externally. A nice to have for later.

**Comment by jrwats** [comment]
Tackling this in https://github.com/facebookincubator/fbt/pull/86
